package kz.divtech.odyssey.rotation.domain.model.trips

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class Ticket(
    val additional_info: @RawValue Any?,
    val api_order_id: Int?,
    val arr_date_time: String?,
    val arr_station_code: String?,
    val arr_station_name: String?,
    val book_user_id: Int?,
    val booked_at: String?,
    val by_watcher: Boolean?,
    val car_class: String?,
    val car_detail: String?,
    val car_number: String?,
    val car_type: Int?,
    val car_type_label: String?,
    val carrier_name: String?,
    val category_name: @RawValue Any?,
    val category_place_param: @RawValue Any?,
    val category_place_param_id: @RawValue Any?,
    val category_place_param_ind: @RawValue Any?,
    val dep_date_time: String?,
    val dep_station_code: String?,
    val dep_station_name: String?,
    val distance: Int?,
    val doc_number: String?,
    val doc_type: String?,
    val express_id: String?,
    val from_old: Int?,
    val id: Int,
    val is_talgo_train: Int?,
    val issue_user_id: Int?,
    val issued_at: String?,
    val max_price: Int?,
    val min_price: Int?,
    val order_id: Int?,
    val place_level: @RawValue Any?,
    val place_otsek_number: Int?,
    val place_select_type: String?,
    val places: List<Place>?,
    val return_commission: String?,
    val return_sum: Int?,
    val return_user_id: Int?,
    val returned_at: String?,
    val seat_level: String?,
    val seat_number: String?,
    val status: String?,
    val sum: Int?,
    val ticket_url: String?,
    val train_display_number: String?,
    val train_number: String?,
    val travcom_issue_download: Int?,
    val travcom_refund_download: Int?
) : Parcelable